#########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    # Useful URL: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=libayatana-appindicator
    - clang
    - gcc
    - git
    - make
    - startup-notification
    - which
    - cmake
    - cmake-extras
    - mate-common
    - gtk3
    - glib2
    - libdbusmenu-gtk3
    - dbus-glib
    - gobject-introspection

  debian:
    # Useful URL: https://salsa.debian.org/debian-ayatana-team/libayatana-appindicator
    - autopoint
    - clang
    - clang-tools
    - g++
    - cppcheck
    - git
    - at-spi2-core
    - cmake
    - cmake-extras
    - cli-common-dev
    - gobject-introspection
    - intltool
    - gtk-doc-tools
    - libxml2-utils
    - libnunit-cil-dev
    - dbus-test-runner
    - xvfb
    - valac
    - mono-devel
    - libglib2.0-dev
    - libgtk-3-dev
    - libgtk2.0-dev
    - gtk-sharp3-gapi
    - libgtk3.0-cil-dev
    - gtk-sharp2-gapi
    - libgtk2.0-cil-dev
    - libdbus-1-dev
    - libdbus-glib-1-dev
    - libdbusmenu-glib-dev
    - libdbusmenu-gtk3-dev
    - libdbusmenu-gtk-dev
    - libgirepository1.0-dev

  ubuntu:
    - autopoint
    - clang
    - clang-tools
    - g++
    - cppcheck
    - git
    - at-spi2-core
    - cmake
    - cmake-extras
    - cli-common-dev
    - gobject-introspection
    - intltool
    - gtk-doc-tools
    - libxml2-utils
    - libnunit-cil-dev
    - dbus-test-runner
    - xvfb
    - valac
    - mono-devel
    - libglib2.0-dev
    - libgtk-3-dev
    - libgtk2.0-dev
    - gtk-sharp3-gapi
    - libgtk3.0-cil-dev
    - gtk-sharp2-gapi
    - libgtk2.0-cil-dev
    - libdbus-1-dev
    - libdbus-glib-1-dev
    - libdbusmenu-glib-dev
    - libdbusmenu-gtk3-dev
    - libdbusmenu-gtk-dev
    - libgirepository1.0-dev

variables:
  - 'CHECKERS="
    -enable-checker deadcode.DeadStores
    -enable-checker alpha.deadcode.UnreachableCode
    -enable-checker alpha.core.CastSize
    -enable-checker alpha.core.CastToStruct
    -enable-checker alpha.core.IdenticalExpr
    -enable-checker alpha.core.SizeofPtr
    -enable-checker alpha.security.ArrayBoundV2
    -enable-checker alpha.security.MallocOverflow
    -enable-checker alpha.security.ReturnPtrRange
    -enable-checker alpha.unix.SimpleStream
    -enable-checker alpha.unix.cstring.BufferOverlap
    -enable-checker alpha.unix.cstring.NotNullTerminated
    -enable-checker alpha.unix.cstring.OutOfBounds
    -enable-checker alpha.core.FixedAddr
    -enable-checker security.insecureAPI.strcpy"'

before_scripts:
  - cd ${START_DIR}
  - if [ ! -d ayatana-ido-build ]; then
  -     git clone --depth 1 https://github.com/AyatanaIndicators/ayatana-ido.git ayatana-ido-build
  - fi
  - cd ayatana-ido-build
  - cmake . -DCMAKE_INSTALL_PREFIX=/usr
  - make
  - make install
  - cd ../
  - rm -Rf ayatana-ido-build/
  -
  - cd ${START_DIR}
  - if [ ! -d libayatana-indicator-build ]; then
  -     git clone --depth 1 https://github.com/AyatanaIndicators/libayatana-indicator.git libayatana-indicator-build
  - fi
  - cd libayatana-indicator-build
  - mkdir -p build/gtk3
  - cd build/gtk3
  - cmake ../../ -DCMAKE_INSTALL_PREFIX=/usr -DFLAVOUR_GTK3=ON
  - make
  - make install
  - cd -
  - mkdir -p build/gtk2
  - cd build/gtk2
  - cmake ../../ -DCMAKE_INSTALL_PREFIX=/usr -DFLAVOUR_GTK2=ON
  - make
  - make install
  - cd -
  - cd ../
  - rm -Rf libayatana-indicator-build/

build_scripts:
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     export CFLAGS+=" -Wsign-compare -Wunused-parameter"
  -     cppcheck --enable=warning,style,performance,portability,information,missingInclude .
  - fi
  -
  - if [ -e ./CMakeLists.txt ]; then
  -     mkdir -p build/gtk3/
  -     cd build/gtk3/
  -     if [ ${DISTRO_NAME} == "debian" ] || [ ${DISTRO_NAME} == "ubuntu" ]; then
  -         scan-build $CHECKERS cmake ../../ -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=ON -DENABLE_TESTS=ON -DFLAVOUR_GTK3=ON
  -     else
  -         scan-build $CHECKERS cmake ../../ -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=ON -DFLAVOUR_GTK3=ON
  -     fi
  -     cd -
  -     mkdir -p build/gtk2/
  -     cd build/gtk2/
  -     if [ ${DISTRO_NAME} == "debian" ] || [ ${DISTRO_NAME} == "ubuntu" ]; then
  -         scan-build $CHECKERS cmake ../../ -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=ON -DENABLE_TESTS=ON -DFLAVOUR_GTK2=ON
  -     else
  -         scan-build $CHECKERS cmake ../../ -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=ON -DFLAVOUR_GTK2=ON
  -     fi
  -     cd -
  - else
  -     exit 1
  - fi
  -
  - if [ $CPU_COUNT -gt 1 ]; then
  -     if [ ${DISTRO_NAME} == "debian" ];then
  -         cd build/gtk3/
  -         scan-build $CHECKERS --keep-cc --use-cc=clang --use-c++=clang++ -o html-report make -j $CPU_COUNT
  -         make clean
  -         cd -
  -         cd build/gtk2/
  -         scan-build $CHECKERS --keep-cc --use-cc=clang --use-c++=clang++ -o html-report make -j $CPU_COUNT
  -         make clean
  -         cd -
  -     fi
  -     cd build/gtk3/
  -     scan-build $CHECKERS --keep-cc -o html-report make -j $CPU_COUNT
  -     cd -
  -     cd build/gtk2/
  -     scan-build $CHECKERS --keep-cc -o html-report make -j $CPU_COUNT
  -     cd -
  - else
  -     if [ ${DISTRO_NAME} == "debian" ];then
  -         cd build/gtk3/
  -         scan-build $CHECKERS --keep-cc --use-cc=clang --use-c++=clang++ -o html-report make
  -         make clean
  -         cd -
  -         cd build/gtk2/
  -         scan-build $CHECKERS --keep-cc --use-cc=clang --use-c++=clang++ -o html-report make
  -         make clean
  -         cd -
  -     fi
  -     cd build/gtk3/
  -     scan-build $CHECKERS --keep-cc -o html-report make
  -     cd -
  -     cd build/gtk2/
  -     scan-build $CHECKERS --keep-cc -o html-report make
  -     cd -
  - fi
  - XVFB_RUN="$(which xvfb-run || true)"
  - if [ ${DISTRO_NAME} == "debian" ] || [ ${DISTRO_NAME} == "ubuntu" ]; then
  -     if [ -e ./CMakeLists.txt ]; then
  -         cd build/gtk3/
  -         ${XVFB_RUN} env CTEST_OUTPUT_ON_FAILURE=1 make test
  -         cd -
  -         cd build/gtk2/
  -         ${XVFB_RUN} env CTEST_OUTPUT_ON_FAILURE=1 make test
  -         cd -
  -     fi
  - fi
