#########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    # Useful URL: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=libayatana-appindicator
    - clang
    - gcc
    - git
    - make
    - startup-notification
    - which
    - cmake
    - cmake-extras
    - glib2
    - glib2-devel
    - gobject-introspection
    - vala
    - gi-docgen
    - dbus-test-runner (AUR)
    - xorg-server-xvfb

  debian:
    # Useful URL: https://salsa.debian.org/debian-ayatana-team/libayatana-appindicator
    - clang
    - clang-tools
    - g++
    - cppcheck
    - git
    - cmake
    - cmake-extras
    - cli-common-dev
    - gobject-introspection
    - gi-docgen
    - dbus-test-runner
    - xvfb
    - valac
    - libglib2.0-dev
    - libgirepository1.0-dev

  ubuntu:
    - clang
    - clang-tools
    - g++
    - cppcheck
    - git
    - cmake
    - cmake-extras
    - cli-common-dev
    - gobject-introspection
    - gi-docgen
    - dbus-test-runner
    - xvfb
    - valac
    - libglib2.0-dev
    - libgirepository1.0-dev

variables:
  - 'CHECKERS="
    -enable-checker deadcode.DeadStores
    -enable-checker alpha.deadcode.UnreachableCode
    -enable-checker alpha.core.CastSize
    -enable-checker alpha.core.CastToStruct
    -enable-checker alpha.core.IdenticalExpr
    -enable-checker alpha.core.SizeofPtr
    -enable-checker alpha.security.ArrayBoundV2
    -enable-checker alpha.security.MallocOverflow
    -enable-checker alpha.security.ReturnPtrRange
    -enable-checker alpha.unix.SimpleStream
    -enable-checker alpha.unix.cstring.BufferOverlap
    -enable-checker alpha.unix.cstring.NotNullTerminated
    -enable-checker alpha.unix.cstring.OutOfBounds
    -enable-checker alpha.core.FixedAddr
    -enable-checker security.insecureAPI.strcpy"'

build_scripts:
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     cppcheck --enable=warning,style,performance,portability,information,missingInclude .
  - fi
  -
  - if [ ${DISTRO_NAME} == "debian" ] || [ ${DISTRO_NAME} == "ubuntu" ]; then
  -     scan-build $CHECKERS cmake ../../ -DCMAKE_VERBOSE_MAKEFILE=ON -DENABLE_TESTS=ON
  - else
  -     scan-build $CHECKERS cmake ../../ -DCMAKE_VERBOSE_MAKEFILE=ON
  - fi
  -
  - if [ $CPU_COUNT -gt 1 ]; then
  -     if [ ${DISTRO_NAME} == "debian" ];then
  -         scan-build $CHECKERS --keep-cc --use-cc=clang --use-c++=clang++ -o html-report make -j $CPU_COUNT
  -         make clean
  -     fi
  - else
  -     if [ ${DISTRO_NAME} == "debian" ];then
  -         scan-build $CHECKERS --keep-cc --use-cc=clang --use-c++=clang++ -o html-report make
  -         make clean
  -     fi
  -     scan-build $CHECKERS --keep-cc -o html-report make
  - fi
  - XVFB_RUN="$(which xvfb-run || true)"
  - if [ ${DISTRO_NAME} == "debian" ] || [ ${DISTRO_NAME} == "ubuntu" ]; then
  -     ${XVFB_RUN} env CTEST_OUTPUT_ON_FAILURE=1 make test
  - fi
