const char * _notification_watcher = 
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
"<node name=\"/StatusNotifierWatcher\">\n"
"	<interface name=\"org.kde.StatusNotifierWatcher\">\n"
"\n"
"<!-- Properties -->\n"
"		<property name=\"ProtocolVersion\" type=\"i\" access=\"read\" />\n"
"		<property name=\"IsStatusNotifierHostRegistered\" type=\"b\" access=\"read\" />\n"
"		<property name=\"RegisteredStatusNotifierItems\" type=\"as\" access=\"read\" />\n"
"\n"
"<!-- Methods -->\n"
"		<method name=\"RegisterStatusNotifierItem\">\n"
"		    <annotation name=\"org.freedesktop.DBus.GLib.Async\" value=\"true\" />\n"
"			<arg type=\"s\" name=\"service\" direction=\"in\" />\n"
"		</method>\n"
"		<method name=\"RegisterStatusNotifierHost\">\n"
"			<arg type=\"s\" name=\"service\" direction=\"in\" />\n"
"		</method>\n"
"		<method name=\"XAyatanaRegisterNotificationApprover\">\n"
"		    <annotation name=\"org.freedesktop.DBus.GLib.Async\" value=\"true\" />\n"
"			<!-- The path where to find the approver interface -->\n"
"			<arg type=\"o\" name=\"path\" direction=\"in\" />\n"
"			<!-- List of categories to approve, none represents all -->\n"
"			<arg type=\"as\" name=\"categories\" direction=\"in\" />\n"
"		</method>\n"
"\n"
"<!-- Signals -->\n"
"		<signal name=\"StatusNotifierItemRegistered\">\n"
"			<arg type=\"s\" name=\"service\" direction=\"out\" />\n"
"		</signal>\n"
"		<signal name=\"StatusNotifierItemUnregistered\">\n"
"			<arg type=\"s\" name=\"service\" direction=\"out\" />\n"
"		</signal>\n"
"		<signal name=\"StatusNotifierHostRegistered\">\n"
"		</signal>\n"
"\n"
"	</interface>\n"
"</node>\n"
;
