/* Generated by dbus-binding-tool; do not edit! */

#include <glib.h>
#include <dbus/dbus-glib.h>

G_BEGIN_DECLS

#ifndef _DBUS_GLIB_ASYNC_DATA_FREE
#define _DBUS_GLIB_ASYNC_DATA_FREE
static
#ifdef G_HAVE_INLINE
inline
#endif
void
_dbus_glib_async_data_free (gpointer stuff)
{
	g_slice_free (DBusGAsyncData, stuff);
}
#endif

#ifndef DBUS_GLIB_CLIENT_WRAPPERS_org_kde_StatusNotifierItem
#define DBUS_GLIB_CLIENT_WRAPPERS_org_kde_StatusNotifierItem

#endif /* defined DBUS_GLIB_CLIENT_WRAPPERS_org_kde_StatusNotifierItem */

G_END_DECLS
